image: node:6

stages:
  - build
  - test

npm-build:
  stage: build
  script:
    - npm install
    - npm run build.prod

npm-test:
  stage: test
  script:
    - npm install
    - export GITLABCI=1
    - npm test
